### ISSUE TITLE
Strange deserts and lakes in eastern USA

### ISSUE THREAD

**Issue by SuperSpruce** [TheOddler/FactorioWorld#24] opened 2022-01-21 17:22 UTC
I don't know how to submit images here but it seems like the map generation is bugged. I am playing on a 1:200 scale world, and have unlocked most of the eastern part of the United States. But there's still some patches not explored yet, and when I uncover them, I get a starkly different environment than what's around it. There is a desert in southern Georgia (the state), a lake in northern Florida, and desert lakes in West Virginia. I don't know what to do to fix this.
![Screenshot 2022-01-21 122004](https://user-images.githubusercontent.com/48099460/150571822-520d3a18-e6c9-48f9-abd6-112401382af2.png)

**Comment by SuperSpruce** [comment] 2022-01-22 21:52
![Screenshot 2022-01-22 165057](https://user-images.githubusercontent.com/48099460/150656616-ee2e01b9-7049-4f9e-b2dc-d818645cb44d.png)
Here is a much more alarming image of what's happening.

**Comment by SuperSpruce** [comment] 2022-01-22 22:12
I did further digging into this, and noticed my mod settings changed automatically to the default!

**Comment by TheOddler** [comment] 2022-01-24 09:04
Aha! Since this is likely not a bug in the mod, I'll close this for now. Glad you figured it out!

**Closed by TheOddler** 2022-01-24 09:04 UTC
